"""Hippo-style trace-augmented shared LoRA trainer.

Same as scripts/train_shared_lora.py, but with a 4-format training corpus:
  1. observation: a paraphrase of each fact (one per fact per user)
  2. factual: "<key>: <value>" (one per fact per user)
  3. qa: "Facts: ... Q: ... A: <gold>" (existing in-context-reasoning samples)
  4. trace: "Facts: ... Q: ... <think>{thinking}</think> A: <gold>" (new)

The trace samples are pre-generated by scripts/generate_trace_corpus.py.

Usage:
    python -m scripts.train_shared_lora_trace \\
        --ckpt-dir $NANOCHAT_BASE_DIR/engram_runs/engram_d20_w1536_optimal \\
        --user-dir $USER_AS_ENGRAM_ROOT/data/users \\
        --train-uids u020 u021 u022 u023 u024 u025 u026 u027 u028 u029 \\
        --trace-file $USER_AS_ENGRAM_ROOT/nanochat_base/shared_lora_d20_trace/traces.jsonl \\
        --format-weights 0.25,0.25,0.25,0.25 \\
        --rank 16 --steps 2000 \\
        --out-dir $USER_AS_ENGRAM_ROOT/nanochat_base/shared_lora_d20_trace/r16
"""
import os
UAE_ROOT = os.environ.get("USER_AS_ENGRAM_ROOT") or (
    os.path.dirname(os.environ["NANOCHAT_BASE_DIR"]) if os.environ.get("NANOCHAT_BASE_DIR")
    else os.getcwd())
import os, sys, json, argparse, time, random
from pathlib import Path

import torch
import torch.nn.functional as F

from nanochat.tokenizer import get_tokenizer
from scripts.insertion_strategies_v2 import load_model
from scripts.sft_baseline import attach_lora, detach_lora


def _norm(a):
    if isinstance(a, list):
        return ", ".join(str(x) for x in a)
    return str(a)


def _completion_prefix(paraphrases, ans):
    for p in paraphrases:
        p = p.rstrip(".")
        if p.endswith(ans):
            return p[: -len(ans)].rstrip()
    return None


def _fact_to_text(f, form="completion"):
    """Render a fact as a training sample."""
    ans = _norm(f["answer"])
    if form == "completion":
        # paraphrase ending in answer
        pref = _completion_prefix(f["paraphrases"], ans)
        if pref is None:
            return None
        return f"{pref} {ans}"
    elif form == "observation":
        # any paraphrase (full sentence)
        if not f["paraphrases"]:
            return None
        # Prefer paraphrases that don't end in the answer (more diverse)
        non_completion = [p for p in f["paraphrases"]
                          if not p.rstrip(".").endswith(ans)]
        chosen = random.choice(non_completion if non_completion else f["paraphrases"])
        return chosen.rstrip(".") + "."
    elif form == "factual":
        # "key: value" form
        return f"{f['key'].replace('_', ' ')}: {ans}"
    return None


def build_corpus(user_jsons, trace_records, max_indirect_per_user=20,
                 format_weights=(0.25, 0.25, 0.25, 0.25), seed=42):
    """Build 4-format training samples.

    Returns a dict {format_name: [strings]}; the trainer samples by format
    weight at each step.
    """
    rng = random.Random(seed)

    obs_samples, fact_samples, qa_samples = [], [], []
    for uj in user_jsons:
        fact_by_key = {f["key"]: f for f in uj["facts"]}

        for f in uj["facts"]:
            # observation
            obs = _fact_to_text(f, "observation")
            if obs:
                obs_samples.append(obs)
            # factual
            ff = _fact_to_text(f, "factual")
            if ff:
                fact_samples.append(ff)
            # completion-fact (kept in qa bucket for backwards-compat with
            # the baseline trainer's training mix)
            cf = _fact_to_text(f, "completion")
            if cf:
                qa_samples.append(cf)

        # In-context reasoning samples (existing format)
        iqs = list(uj["indirect_qa"])
        rng.shuffle(iqs)
        used = 0
        for iq in iqs:
            if used >= max_indirect_per_user:
                break
            req = iq.get("required_fact_keys") or []
            if not req:
                continue
            relevant = []
            for k in req:
                if k not in fact_by_key:
                    continue
                f = fact_by_key[k]
                ans = _norm(f["answer"])
                pref = _completion_prefix(f["paraphrases"], ans)
                if pref is None:
                    relevant.append(f"{k.replace('_', ' ')}: {ans}")
                else:
                    relevant.append(f"{pref} {ans}")
            if not relevant:
                continue
            block = ". ".join(relevant) + "."
            gold = _norm(iq["answer"])
            qa_samples.append(
                f"Facts: {block}\nQ: {iq['question']}\nA: {gold}"
            )
            used += 1

    # Trace samples (only retained traces; gold is checked already).
    # Variant: use the teacher's elaborated answer (not the bare gold) as
    # the supervision target; DROP the explicit <think> block from the
    # training sequence so the eval-time "Q: ... A:" template doesn't
    # induce the student to expect a <think> slot. This keeps the
    # distillation signal (teacher's reasoning-influenced answer) while
    # matching user-as-engram's eval format.
    trace_samples = []
    for r in trace_records:
        if not r.get("retained", False):
            continue
        teacher_answer = r.get("answer", "").strip()
        if not teacher_answer:
            teacher_answer = r["gold"]
        sample = (f"Facts: {r['fact_block']}\nQ: {r['question']}\n"
                  f"A: {teacher_answer}")
        trace_samples.append(sample)

    print(f"  observation samples: {len(obs_samples)}")
    print(f"  factual samples:     {len(fact_samples)}")
    print(f"  qa samples:          {len(qa_samples)}")
    print(f"  trace samples:       {len(trace_samples)}")

    return {
        "obs": obs_samples,
        "fact": fact_samples,
        "qa": qa_samples,
        "trace": trace_samples,
    }, format_weights


def train_shared_lora_trace(model, tokenizer, corpus, weights, device,
                            rank, steps, lr, alpha=None, max_len=512,
                            log_every=100, seed=42):
    if alpha is None:
        alpha = 2 * rank
    bos = tokenizer.get_bos_token_id()
    rng = random.Random(seed)

    # Pre-tokenise per format
    token_by_format = {}
    for fmt, samples in corpus.items():
        toks = []
        for s in samples:
            ids = tokenizer.encode(s, prepend=bos)
            if len(ids) > max_len:
                ids = ids[:max_len]
            toks.append(ids)
        token_by_format[fmt] = toks

    # Build a sampling list of (format, weight) pairs
    fmt_list = ["obs", "fact", "qa", "trace"]
    fmt_w = list(weights)
    # Drop formats with zero samples
    fmt_present = [(f, w) for f, w in zip(fmt_list, fmt_w)
                   if token_by_format.get(f) and w > 0]
    total_w = sum(w for _, w in fmt_present)
    fmt_probs = [(f, w / total_w) for f, w in fmt_present]

    grad_snap = []
    for p in model.parameters():
        grad_snap.append(p.requires_grad)
        p.requires_grad_(False)

    handles = attach_lora(model, rank=rank, alpha=alpha)
    lora_params = []
    for _, _, lora, _ in handles:
        for p in lora.parameters():
            p.requires_grad_(True)
            lora_params.append(p)
    n_lora_params = sum(p.numel() for p in lora_params)
    print(f"  LoRA rank={rank}, alpha={alpha}, trainable params={n_lora_params:,}")
    print(f"  Format mix: {fmt_probs}")

    optim = torch.optim.Adam(lora_params, lr=lr)
    t0 = time.time()
    running = []
    per_fmt_running = {f: [] for f, _ in fmt_probs}

    for step in range(steps):
        # Sample a format by weight, then a sample within that format
        r = rng.random()
        cum = 0.0
        chosen_fmt = fmt_probs[-1][0]
        for f, p in fmt_probs:
            cum += p
            if r <= cum:
                chosen_fmt = f
                break
        toks_list = token_by_format[chosen_fmt]
        i = rng.randrange(len(toks_list))
        ids = toks_list[i]
        x = torch.tensor([ids], dtype=torch.long, device=device)
        logits = model(x)
        if logits.size(1) < 2:
            continue
        shift_logits = logits[0, :-1, :].float()
        shift_labels = x[0, 1:]
        loss = F.cross_entropy(shift_logits, shift_labels)
        grads = torch.autograd.grad(loss, lora_params, create_graph=False)
        for p, g in zip(lora_params, grads):
            if p.grad is None: p.grad = g.clone()
            else: p.grad.copy_(g)
        optim.step()
        optim.zero_grad()
        running.append(loss.item())
        per_fmt_running[chosen_fmt].append(loss.item())
        if (step + 1) % log_every == 0:
            avg = sum(running[-log_every:]) / log_every
            fmt_avgs = []
            for f in per_fmt_running:
                recent = per_fmt_running[f][-log_every:]
                if recent:
                    fmt_avgs.append(f"{f}={sum(recent)/len(recent):.2f}")
            print(f"  step {step+1}/{steps}  loss(avg{log_every})={avg:.3f}  "
                  f"[{' '.join(fmt_avgs)}]  elapsed {time.time()-t0:.0f}s")

    return handles, grad_snap, time.time()-t0, n_lora_params


def save_lora_state(handles, out_dir):
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    state = {}
    for name, _, lora, _ in handles:
        for k, v in lora.state_dict().items():
            state[f"{name}.{k}"] = v.detach().cpu()
    torch.save(state, out_dir / "lora_state.pt")
    return out_dir / "lora_state.pt"


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--ckpt-dir", required=True)
    p.add_argument("--user-dir", default=f"{UAE_ROOT}/data/users")
    p.add_argument("--train-uids", nargs="+",
                   default=[f"u{i:03d}" for i in range(20, 30)])
    p.add_argument("--trace-file", required=True,
                   help="JSONL of teacher traces from generate_trace_corpus.py")
    p.add_argument("--format-weights", default="0.25,0.25,0.25,0.25",
                   help="obs,fact,qa,trace weights (must sum to 1)")
    p.add_argument("--rank", type=int, default=16)
    p.add_argument("--steps", type=int, default=2000)
    p.add_argument("--lr", type=float, default=3e-4)
    p.add_argument("--max-indirect-per-user", type=int, default=20)
    p.add_argument("--max-len", type=int, default=512)
    p.add_argument("--out-dir", required=True)
    p.add_argument("--seed", type=int, default=42)
    args = p.parse_args()

    random.seed(args.seed)
    torch.manual_seed(args.seed)

    weights = tuple(float(x) for x in args.format_weights.split(","))
    assert len(weights) == 4 and abs(sum(weights) - 1.0) < 1e-3, \
        f"format-weights must be 4 floats summing to 1.0; got {weights}"

    print(f"Loading user JSONs from {args.user_dir} for "
          f"{len(args.train_uids)} train users...")
    user_jsons = []
    for uid in args.train_uids:
        with open(Path(args.user_dir) / f"{uid}.json") as f:
            user_jsons.append(json.load(f))

    print(f"Loading traces from {args.trace_file}...")
    trace_records = []
    with open(args.trace_file) as f:
        for line in f:
            trace_records.append(json.loads(line))
    print(f"  {len(trace_records)} traces, "
          f"{sum(1 for r in trace_records if r.get('retained', False))} retained")

    print("Building 4-format corpus...")
    corpus, weights = build_corpus(user_jsons, trace_records,
                                   max_indirect_per_user=args.max_indirect_per_user,
                                   format_weights=weights, seed=args.seed)

    device = "cuda" if torch.cuda.is_available() else "cpu"
    tokenizer = get_tokenizer()
    print(f"Loading model from {args.ckpt_dir}...")
    model, _ = load_model(args.ckpt_dir, tokenizer, device)
    model.eval()

    print(f"Training shared LoRA: rank={args.rank}, steps={args.steps}, "
          f"lr={args.lr}, max_len={args.max_len}")
    handles, grad_snap, train_time, n_params = train_shared_lora_trace(
        model, tokenizer, corpus, weights, device,
        rank=args.rank, steps=args.steps, lr=args.lr,
        max_len=args.max_len, seed=args.seed,
    )

    print(f"Training done in {train_time:.0f}s. Saving to {args.out_dir}...")
    save_path = save_lora_state(handles, args.out_dir)

    # Metadata
    meta = {
        "ckpt_dir": args.ckpt_dir,
        "train_uids": args.train_uids,
        "trace_file": args.trace_file,
        "format_weights": list(weights),
        "rank": args.rank,
        "alpha": 2 * args.rank,
        "steps": args.steps,
        "lr": args.lr,
        "max_len": args.max_len,
        "seed": args.seed,
        "train_time_s": train_time,
        "n_lora_params": n_params,
        "corpus_sizes": {f: len(s) for f, s in corpus.items()},
    }
    with open(Path(args.out_dir) / "meta.json", "w") as f:
        json.dump(meta, f, indent=2)
    print(f"Saved to {save_path}")
    print(f"Wrote {Path(args.out_dir) / 'meta.json'}")


if __name__ == "__main__":
    main()
